### ISSUE TITLE
Train/test split of SQuAD used in your paper

### ISSUE THREAD

**Issue by tangyixuan** [KazutoshiShinoda/VQAG#2]
Could you release the train/test split of SQuAD used in the experiments of your paper? Thanks

**Comment by KazutoshiShinoda** [comment]
@tangyixuan 
Thank you for your question.
The train/dev/test split of SQuAD used in our paper is the same as Du et al. (2017).
The split is released at https://github.com/tomhosking/squad-du-split

Du et al. 2017. Learning to Ask: Neural Question Generation for Reading Comprehension (https://arxiv.org/abs/1705.00106)
